Bloggie.Web/Pages/Admin/Blogs/Add.cshtml.cs
using System.Text.Json;
using Bloggie.Web.Data;
using Bloggie.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace Bloggie.Web.Pages.Admin.Blogs;


[Authorize(Roles = "Admin")]
public class AddModel : PageModel
{
    public IBlogPostRepository BlogPostRepository { get; }

    //read only DBcontext used for seedeing purposes
    private readonly IBlogPostRepository blogPostRepository; 
    
    //Binding domainmodels, using AddBlogPost
    [BindProperty]
    public AddBlogPost AddBlogPostRequest { get; set; }

    [BindProperty]
    public IFormFile FeaturedImage { get; set; }
    //Default Constructor

    [BindProperty]
    public string Tags { get; set; }
    public AddModel(IBlogPostRepository blogPostRepository)
    {
        this.blogPostRepository = blogPostRepository; 
    }
    
    public void OnGet()
    {
        
    }

    public async Task<IActionResult> OnPost()
    {

        //Published Datetime varaible is different from the legacy code, should be PublishedDate
        var blogpost = new BlogPost()
        {
            Heading = AddBlogPostRequest.Heading,
            PageTitle = AddBlogPostRequest.PageTitle,
            Content = AddBlogPostRequest.Content,
            ShortDescription = AddBlogPostRequest.ShortDescription,
            FeaturedImageURL = AddBlogPostRequest.FeaturedImageURL,
            UrlHandle = AddBlogPostRequest.UrlHandle,
            PublishedDateTime = AddBlogPostRequest.PublishedDateTime,
            Author = AddBlogPostRequest.Author,
            Visible = AddBlogPostRequest.Visible,
            Tags = new List<Tag>(Tags.Split(',').Select(x => new Tag(){Name = x.Trim()})) 
        };

        await blogPostRepository.AddAsync(blogpost);

        var notification = new Notification
        {
            Type = Enums.NotificationType.Success,
            Message = "New Blog Created (Written by me)"
        };
        
        //What the fuck is this 
        TempData["Notification"] =  JsonSerializer.Serialize(notification);
        return RedirectToPage("/Admin/Blogs/List");
    }
}

Bloggie.Web/Pages/Admin/Blogs/Edit.cshtml.cs
using System.Data;
using System.Text.Json;
using Bloggie.Web.Data;
using Bloggie.Web.Enums;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

namespace Bloggie.Web.Pages.Admin.Blogs;


[Authorize(Roles = "Admin")]
public class EditModel : PageModel
{
    private readonly IBlogPostRepository blogPostRepository;

    private readonly BloggieDbContext bloggieDbContext;
    
    [BindProperty]
    public BlogPost BlogPost { get; set; }
    
    [BindProperty]
    public IFormFile FeaturedImage { get; set; }

    [BindProperty]
    public string Tags { get; set; }    
    public EditModel(IBlogPostRepository blogPostRepository)
    {
        this.blogPostRepository = blogPostRepository;
    }
    public async Task OnGet(Guid id)
    {
        BlogPost = await blogPostRepository.GetAsync(id);

        if (BlogPost != null && BlogPost.Tags != null)
        {
            Tags = string.Join(',', BlogPost.Tags.Select(x => x.Name));
        }
    }

    public async Task<IActionResult> OnPostEdit()
    {
        try
        {
            BlogPost.Tags = new List<Tag>(Tags.Split(',').Select(x => new Tag(){ Name = x.Trim() })); 
            await blogPostRepository.UpdateAsync(BlogPost);

            ViewData["Notification"] = new Notification
            {
                Message = "Record Updated Successfully",
                Type = Enums.NotificationType.Success
            };
        }
        catch (Exception ex)
        {
            ViewData["Notification"] = new Notification
            {
                Type = Enums.NotificationType.Error,
                Message = "Something Went Wrong (Written by me)"
            };
            
        }

        //return RedirectToPage("/Admin/Blogs/List"); 
        return Page();
    }

    public async Task<IActionResult> OnPostDelete()
    {
        //creates an domain model 
        var deleted = await blogPostRepository.DeleteAsync(BlogPost.Id);

        if (deleted)
        {
            var notification = new Notification
            {
                Type = Enums.NotificationType.Success,
                Message = "Blog Deleted (Written by me)"
            };
        
            //What the fuck is this 
            TempData["Notification"] =  JsonSerializer.Serialize(notification);
            
            return RedirectToPage("/admin/blogs/list");
        }
        return Page(); 
    }
}

Bloggie.Web/Pages/Admin/Blogs/List.cshtml.cs
using System.Text.Json;
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Bloggie.Web.Pages.Admin.Blogs;

[Authorize(Roles = "Admin")]
public class ListModel : PageModel
{
    private readonly IBlogPostRepository blogPostRepository; 
    public List<BlogPost> BlogPosts { get; set; }
    public ListModel(IBlogPostRepository blogPostRepository)
    {
        this.blogPostRepository = blogPostRepository; 
    }
    public async Task OnGet()
    {
        
        var notificationJson = (string)TempData["Notification"];
        if (notificationJson != null)
        {
            ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(notificationJson.ToString());
        }
        BlogPosts = (await blogPostRepository.GetAllAsync())?.ToList(); 
    }
}

Bloggie.Web/Pages/Admin/Blogs/tiptap.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bloggie.Web.Pages.Admin.Blogs;

public class tiptap : PageModel
{
    public void OnGet()
    {
        
    }
}

Bloggie.Web/Pages/Blog/Details.cshtml.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bloggie.Web.Pages.Blog;

public class Details : PageModel
{
    private readonly IBlogPostRepository _blogPostRepository;
    private readonly IBlogPostLikeRepository _blogPostLikeRepository;
    private readonly SignInManager<IdentityUser> _signInManager;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly IBlogPostCommentRepository _blogPostCommentRepository;

    public List<BlogComment> Comments { get; set; }
    public BlogPost BlogPost { get; set; }
   
    public int TotalLikes { get; set; }

    public bool Liked { get; set; }
    
    [BindProperty]
    public Guid BlogPostId { get; set; }
    
    
    [BindProperty]
    public string CommentDescription { get; set; }
    


    public Details(IBlogPostRepository blogPostRepository, 
        IBlogPostLikeRepository blogPostLikeRepository,
        SignInManager<IdentityUser> signInManager,
        UserManager<IdentityUser> userManager,
        IBlogPostCommentRepository blogPostCommentRepository)
    {
        _blogPostRepository = blogPostRepository;
        _blogPostLikeRepository = blogPostLikeRepository;
        _signInManager = signInManager;
        _userManager = userManager;
        _blogPostCommentRepository = blogPostCommentRepository;
    }
    public async Task<IActionResult> OnGet(string urlHandle)
    {
        BlogPost = await _blogPostRepository.GetAsync(urlHandle);

        if (BlogPost != null)
        {
            BlogPostId = BlogPost.Id; 
            if (_signInManager.IsSignedIn(User))
                {
                    var likes = await _blogPostLikeRepository.GetLikesForBlog(BlogPost.Id);
                    var userId = _userManager.GetUserId(User);
                    Liked = likes.Any(x => x.UserId == Guid.Parse(userId));
                    await GetComments(); 
                    var blogPostComments =  await _blogPostCommentRepository.GetAllAsync(BlogPost.Id); 
                }

            TotalLikes = await _blogPostLikeRepository.GetTotalLikesForBlog(BlogPost.Id);
            
        }
        return Page(); 
    }

    public async Task<IActionResult> OnPost(string urlHandle)
    {
        if(_signInManager.IsSignedIn(User) && !string.IsNullOrWhiteSpace(CommentDescription)){

            var userId = _userManager.GetUserId(User);
            var comment = new BlogPostComment()
            {

                BlogPostid = BlogPostId,
                Description = CommentDescription,
                DateAdded = DateTime.Now,
                UserId = Guid.Parse(userId)
            };
            await _blogPostCommentRepository.AddAsync(comment);

        }
        return RedirectToPage("/Blog/Details", new { urlHandle = urlHandle });
    }

    private async Task GetComments()
    {
        var blogPostComments = await _blogPostCommentRepository.GetAllAsync((BlogPost.Id));

        var blogCommentsViewModel = new List<BlogComment>(); 
        foreach (var blogPostComment in blogPostComments)
        {
            blogCommentsViewModel.Add(new BlogComment
            {
                DateAdded = blogPostComment.DateAdded, 
                Description = blogPostComment.Description, 
                Username = (await _userManager.FindByIdAsync(blogPostComment.UserId.ToString())).UserName
            });
        }

        Comments = blogCommentsViewModel; 
    }
}

Bloggie.Web/Pages/Admin/Blogs/Add.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.AddModel

@{
   
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Add Blog Post</h1>
    </div> 
</div>


<div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" aria-describedby="Heading" asp-for="AddBlogPostRequest.Heading">
            </div>

            <div class="mb-3">
                <label for="pageTitle" class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" aria-describedby="pageTitle" asp-for="AddBlogPostRequest.PageTitle">
            </div>

            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="AddBlogPostRequest.Content"></textarea>
            </div>

            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description</label>
                <input asp-for="AddBlogPostRequest.ShortDescription" class="form-control" id="shortDescription">
            </div>
            
            <div class="mb-3">
                <label for="featureImageUpload" class="form-label">Featured Image Upload</label>
                <input type="file" id="featureImageUpload" asp-for="FeaturedImage"/>
                <img src="" id="featuredImageDisplay" style="display:none; width: 300px;" />
            </div>
            
            <div class="mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                <input   class ="form-control" id="featuredImageUrl" asp-for="AddBlogPostRequest.FeaturedImageURL">
            </div>

            <div class="mb-3">
                <label for="urlHandle" class="form-label">urlHandle</label>
                <input class="form-control" id="urlHandle" asp-for="AddBlogPostRequest.UrlHandle">
            </div>

            <div class="mb-3">
                <label for="PublishedDate" class="form-label">Publish Date</label>
                <input name = "PublishedDate" type="date" class="form-control" id="PublishedDate" asp-for="AddBlogPostRequest.PublishedDateTime">
            </div>
            
            <div class="mb-3">
                <label for="" class="form-label">Tags (comma seperated)</label>
                <input type="text" class="form-control" id="tags" asp-for="Tags"/> 
            </div>
            
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>

            <div class="mb-3">
                <label for="Author" class="form-label">Author</label>
                <input class="form-control" id="Author" asp-for="AddBlogPostRequest.Author">
            </div>
            
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>

        </form>
    </div>
</div>

@section Scripts
{
    <script>
        
        
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images'
        }); 
        
        const featuredimageUploadElement = document.getElementById('featureImageUpload');
        const featureImageUrl = document.getElementById('featuredImageUrl'); 
        const featuredImageDisplay = document.getElementById('featuredImageDisplay')
        
        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]); 
            
            let data = new FormData(); 
            data.append('file', e.target.files[0]); 
            
            await fetch('/api/images',
             {method: 'POST',
              headers: {
                'Accept': '*/*', 
              },
              body: data
            }).then(response => response.json()) 
            .then(result => {
                    featureImageUrl.value = result.link; 
                    featuredImageDisplay.style.display = 'block';
                    featuredImageDisplay.src = result.link; 
        }); 
        }
        
        
        featuredimageUploadElement.addEventListener('change', uploadFeaturedImage);
    
    </script>
}

Bloggie.Web/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"
@model Bloggie.Web.Pages.Admin.Blogs.EditModel

@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Edit Blog Post</h1>
    </div> 
</div>
 
<partial name="_Notification"/>

@if (Model.BlogPost != null)
{
    <div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="id" class="form-label">Id</label>
                <input type="text" class="form-control" id="id" aria-describedby="id" asp-for="BlogPost.Id" >
            </div>
            <div class="mb-3">
                <label for="Heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="Heading" aria-describedby="Heading" asp-for="BlogPost.Heading" >
            </div>

            <div class="mb-3">
                <label for="pageTitle" class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" aria-describedby="pageTitle" asp-for="BlogPost.PageTitle">
            </div>

            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="BlogPost.Content"></textarea>
            </div>

            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description</label>
                <input asp-for="BlogPost.ShortDescription" class="form-control" id="shortDescription">
            </div>

            <div class="mb-3">
                <label for="featureImageUpload" class="form-label">Featured Image Upload</label>
                <input type="file" id="featureImageUpload" asp-for="FeaturedImage"/>
                
                @if (Model.BlogPost.FeaturedImageURL != null)
                {
                    <img src="@Model.BlogPost.FeaturedImageURL" id="featuredImageDisplay" style=" width: 300px;" />
                }
                else
                {
                    <img src="" id="featuredImageDisplay" style="display:none; width: 300px;" />

                }
            </div>
            
            <div class="mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                <input   class ="form-control" id="featuredImageUrl" asp-for="BlogPost.FeaturedImageURL">
            </div>

            <div class="mb-3">
                <label for="urlHandle" class="form-label">urlHandle</label>
                <input class="form-control" id="urlHandle" asp-for="BlogPost.UrlHandle">
            </div>

            <div class="mb-3">
                <label for="PublishedDate" class="form-label">Publish Date</label>
                <input name = "PublishedDate" type="date" class="form-control" id="PublishedDate" asp-for="BlogPost.PublishedDateTime">
            </div>
            
            <div class="mb-3">
                <label class="form-control" for="tags">Tags (*comma seperated)</label>
                <input type="text" id="tags" class="form-control" asp-for="Tags"/> 
            </div>
            
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="BlogPost.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>

            <div class="mb-3">
                <label for="Author" class="form-label">Author</label>
                <input class="form-control" id="Author" asp-for="BlogPost.Author">
            </div>
            
            <div class="mb-3 d-flex justify-content-between">
                <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>
                
                <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
            </div>

        </form>
    </div>
</div>
}
else
{
    <div class="container">
        <p> Oh no! Blog Post Not Found...</p>
    </div>
}

@section Scripts
{
    <script>
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images'
        });

        const featuredimageUploadElement = document.getElementById('featureImageUpload');
        const featureImageUrl = document.getElementById('featuredImageUrl');
        const featuredImageDisplay = document.getElementById('featuredImageDisplay')

        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images',
                {method: 'POST',
                    headers: {
                        'Accept': '*/*',
                    },
                    body: data
                }).then(response => response.json())
                .then(result => {
                    featureImageUrl.value = result.link;
                    featuredImageDisplay.style.display = 'block';
                    featuredImageDisplay.src = result.link;
                });
        }


        featuredimageUploadElement.addEventListener('change', uploadFeaturedImage);
    </script>
}

Bloggie.Web/Pages/Admin/Blogs/List.cshtml
@page
@using Microsoft.EntityFrameworkCore
@model Bloggie.Web.Pages.Admin.Blogs.ListModel

@{
   
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>All Blog Posts</h1>
    </div>
</div>

<partial name="_Notification"/>
@if (Model.BlogPosts != null && Model.BlogPosts.Any())
{
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <td>Id</td>
                <td>Heading</td>
                <td> </td>
            </tr>
            </thead>
            <tbody>
            @foreach (var blogPost in Model.BlogPosts)
            {
                <tr>
                    <td>@blogPost.Id</td>
                    <td>@blogPost.Heading</td>
                    <td><a href="/Admin/Blogs/Edit/@blogPost.Id">View</a></td>
                </tr>
            }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="container">
        <p> No Blog Posts yet... try add some!</p>
    </div>
}

Bloggie.Web/Pages/Admin/Blogs/tiptap.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.tiptap

@{

}

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
</head>
<body>
<div class="element"></div>
<script type="module">
    import { Editor } from 'https://esm.sh/@@tiptap/core'
    import StarterKit from 'https://esm.sh/@@tiptap/starter-kit'
    const editor = new Editor({
        element: document.querySelector('.element'),
        extensions: [StarterKit],
        content: '<p>Hello World!</p>',
    })
</script>
</body>
</html>